package recipe

import (
	"fmt"
	"regexp"
	"strings"
)

var placeholder = regexp.MustCompile(`\{\{(\w+)\}\}`)

// Substitute replaces {{param}} placeholders in s with values from params,
// erroring on any unknown placeholder.
func Substitute(s string, params map[string]string) (string, error) {
	var missing string
	out := placeholder.ReplaceAllStringFunc(s, func(m string) string {
		name := placeholder.FindStringSubmatch(m)[1]
		v, ok := params[name]
		if !ok {
			missing = name
			return m
		}
		return v
	})
	if missing != "" {
		return "", fmt.Errorf("unknown placeholder {{%s}}", missing)
	}
	return out, nil
}

// RenderProfile builds the .env.<name> file body for a recipe with the given
// resolved params.
func RenderProfile(r Recipe, params map[string]string) (string, error) {
	var b strings.Builder
	if r.Description != "" {
		fmt.Fprintf(&b, "# desc: %s\n", r.Description)
	}
	fmt.Fprintf(&b, "# generated by env-garden from recipe %s\n", r.Key())
	for _, e := range r.Env {
		val, err := Substitute(e.Value, params)
		if err != nil {
			return "", fmt.Errorf("env %s: %w", e.Key, err)
		}
		fmt.Fprintf(&b, "export %s=%s\n", e.Key, val)
	}
	return b.String(), nil
}
