package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/stjbrown/env-garden/internal/profile"
	"github.com/spf13/cobra"
)

func newRenderCmd() *cobra.Command {
	var (
		out          string
		resolve      bool
		forceResolve bool
	)
	c := &cobra.Command{
		Use:   "render <profile>",
		Short: "Write a profile to a project env file",
		Long: "Materialize a profile as a .env file for an app to consume.\n\n" +
			"By default, op:// references are written verbatim (no secrets on disk).\n" +
			"--resolve writes real values, but only if the output is git-ignored.\n" +
			"--force-resolve writes real values without the git-ignore check.",
		Args:              cobra.ExactArgs(1),
		ValidArgsFunction: completeProfiles,
		RunE: func(cmd *cobra.Command, args []string) error {
			p, err := profile.Load(args[0])
			if err != nil {
				if os.IsNotExist(err) {
					return fmt.Errorf("no profile %q (try: eg list)", args[0])
				}
				return err
			}
			doResolve := resolve || forceResolve

			absOut, err := filepath.Abs(out)
			if err != nil {
				return err
			}
			if doResolve && !forceResolve {
				if err := guardGitIgnored(absOut); err != nil {
					return err
				}
			}

			content, err := renderContent(p, doResolve)
			if err != nil {
				return err
			}
			if err := os.WriteFile(absOut, []byte(content), 0o600); err != nil {
				return err
			}
			mode := "references"
			if doResolve {
				mode = "resolved values"
			}
			fmt.Fprintf(os.Stderr, "eg: wrote %d vars (%s) to %s\n", len(p.Vars), mode, out)
			return nil
		},
	}
	c.Flags().StringVarP(&out, "out", "o", ".env", "output file path")
	c.Flags().BoolVar(&resolve, "resolve", false, "resolve op:// refs to real values (requires git-ignored output)")
	c.Flags().BoolVar(&forceResolve, "force-resolve", false, "resolve op:// refs without the git-ignore safety check")
	return c
}

// renderContent builds the .env file body. When resolve is false, references
// are emitted verbatim (safe, no secrets on disk); when true, every value is a
// real literal resolved from 1Password as needed.
func renderContent(p *profile.Profile, resolve bool) (string, error) {
	var b strings.Builder
	if p.Desc != "" {
		fmt.Fprintf(&b, "# %s\n", p.Desc)
	}
	fmt.Fprintf(&b, "# generated by env-garden from profile %q\n", p.Name)

	if resolve {
		pairs, err := resolvePairs(p)
		if err != nil {
			return "", err
		}
		for _, kv := range pairs {
			fmt.Fprintf(&b, "%s=%s\n", kv.Key, dotenvQuote(kv.Value))
		}
		return b.String(), nil
	}

	for _, v := range p.Vars {
		if v.IsRef {
			// Raw op:// reference, unquoted so `op inject`/`op run` can find it.
			fmt.Fprintf(&b, "%s=%s\n", v.Key, v.Raw)
		} else {
			fmt.Fprintf(&b, "%s=%s\n", v.Key, dotenvQuote(v.Raw))
		}
	}
	return b.String(), nil
}

// dotenvQuote quotes a value for a .env file: bare when safe, otherwise
// double-quoted with \, ", and newline escaped (the common dotenv dialect).
func dotenvQuote(s string) string {
	if s != "" && !strings.ContainsAny(s, " \t\r\n\"'#$`\\") {
		return s
	}
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

// guardGitIgnored verifies absPath is ignored by git before secrets are written
// to it. git check-ignore -q: exit 0 = ignored, 1 = not ignored, 128 = not a
// repo / error. A non-repo is treated as unprotected (refused), not safe.
func guardGitIgnored(absPath string) error {
	cmd := exec.Command("git", "check-ignore", "-q", absPath)
	cmd.Dir = filepath.Dir(absPath)
	err := cmd.Run()
	if err == nil {
		return nil // ignored — safe
	}
	rel := filepath.Base(absPath)
	if code := exitCode(err); code == 1 {
		return fmt.Errorf("refusing to write secrets to %s: it is not git-ignored.\n"+
			"  add it to .gitignore (echo '%s' >> .gitignore) and retry, or use --force-resolve",
			rel, rel)
	}
	return fmt.Errorf("refusing to write secrets to %s: not inside a git repository, so there is no .gitignore protection.\n"+
		"  use --force-resolve if you really want real values on disk here", rel)
}

// exitCode extracts the process exit code from an exec error, or -1.
func exitCode(err error) int {
	if ee, ok := err.(*exec.ExitError); ok {
		return ee.ExitCode()
	}
	return -1
}
