package toolconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	toml "github.com/pelletier/go-toml/v2"
)

var providerIDPattern = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)

// reserved provider IDs that Codex defines itself.
var reservedProviders = map[string]bool{"openai": true, "ollama": true, "lmstudio": true}

// CodexParams are the inputs needed to wire a custom Codex provider.
type CodexParams struct {
	ProviderID string // [model_providers.<id>] and the --profile name
	BaseURL    string
	Model      string
}

// ApplyCodex ensures configPath contains a [model_providers.<id>] block for an
// OpenAI-compatible endpoint and writes a per-profile overlay file so the user
// can select it with `codex --profile <id>`. The main config is patched by
// append (preserving existing content and comments); an existing block for the
// same id is left untouched. configPath and overlays are backed up before any
// change.
func ApplyCodex(configPath string, p CodexParams) (string, error) {
	if p.ProviderID == "" {
		return "", fmt.Errorf("codex: provider id is required")
	}
	if !providerIDPattern.MatchString(p.ProviderID) {
		return "", fmt.Errorf("codex: invalid provider id %q (use letters, digits, - and _)", p.ProviderID)
	}
	if reservedProviders[p.ProviderID] {
		return "", fmt.Errorf("codex: provider id %q is reserved by Codex; choose another", p.ProviderID)
	}
	if p.BaseURL == "" {
		return "", fmt.Errorf("codex: base_url is required")
	}

	var notes []string

	// --- main config.toml: add the provider block if absent ---
	existing, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return "", err
	}
	present, err := providerPresent(existing, p.ProviderID)
	if err != nil {
		return "", fmt.Errorf("codex: parsing %s: %w", configPath, err)
	}
	if present {
		notes = append(notes, fmt.Sprintf("[model_providers.%s] already present in %s — left unchanged", p.ProviderID, tildeShort(configPath)))
	} else {
		block, err := marshalProviderBlock(p)
		if err != nil {
			return "", err
		}
		if bak, err := backup(configPath); err != nil {
			return "", err
		} else if bak != "" {
			notes = append(notes, "backed up "+tildeShort(configPath)+" -> "+filepath.Base(bak))
		}
		updated := appendBlock(existing, block)
		if err := atomicWrite(configPath, updated, 0o600); err != nil {
			return "", err
		}
		notes = append(notes, fmt.Sprintf("added [model_providers.%s] to %s", p.ProviderID, tildeShort(configPath)))
	}

	// --- overlay file: eg-owned, regenerated each time ---
	overlayPath := filepath.Join(filepath.Dir(configPath), p.ProviderID+".config.toml")
	overlay := map[string]any{"model_provider": p.ProviderID}
	if p.Model != "" {
		overlay["model"] = p.Model
	}
	ob, err := toml.Marshal(overlay)
	if err != nil {
		return "", err
	}
	header := fmt.Sprintf("# generated by env-garden — select with: codex --profile %s\n", p.ProviderID)
	if bak, err := backup(overlayPath); err != nil {
		return "", err
	} else if bak != "" {
		notes = append(notes, "backed up "+filepath.Base(overlayPath)+" -> "+filepath.Base(bak))
	}
	if err := atomicWrite(overlayPath, append([]byte(header), ob...), 0o600); err != nil {
		return "", err
	}
	notes = append(notes, "wrote overlay "+tildeShort(overlayPath))
	notes = append(notes, fmt.Sprintf("run Codex with: codex --profile %s", p.ProviderID))

	return strings.Join(notes, "\n    "), nil
}

// providerPresent reports whether config already defines model_providers.<id>.
func providerPresent(config []byte, id string) (bool, error) {
	if len(config) == 0 {
		return false, nil
	}
	var doc map[string]any
	if err := toml.Unmarshal(config, &doc); err != nil {
		return false, err
	}
	mp, ok := doc["model_providers"].(map[string]any)
	if !ok {
		return false, nil
	}
	_, ok = mp[id]
	return ok, nil
}

// marshalProviderBlock returns the TOML for a single [model_providers.<id>]
// table with the OpenAI-compatible settings Codex needs. The header is written
// directly (the id is pre-validated) and only the field lines are marshaled, so
// no bare [model_providers] parent header is emitted — that would redefine the
// table and break files that already declare another provider.
func marshalProviderBlock(p CodexParams) ([]byte, error) {
	fields := map[string]any{
		"name":     p.ProviderID + " (env-garden)",
		"base_url": p.BaseURL,
		"env_key":  "OPENAI_API_KEY",
		"wire_api": "responses",
	}
	body, err := toml.Marshal(fields)
	if err != nil {
		return nil, err
	}
	header := fmt.Sprintf("[model_providers.%s]\n", p.ProviderID)
	return append([]byte(header), body...), nil
}

// appendBlock joins an existing config and a new block with clean spacing.
func appendBlock(existing, block []byte) []byte {
	var b strings.Builder
	if len(existing) > 0 {
		b.Write(existing)
		if !strings.HasSuffix(string(existing), "\n") {
			b.WriteByte('\n')
		}
		b.WriteByte('\n')
	}
	b.WriteString("# added by env-garden\n")
	b.Write(block)
	return []byte(b.String())
}

// tildeShort replaces the home dir prefix with ~ for friendlier messages.
func tildeShort(path string) string {
	home, err := os.UserHomeDir()
	if err != nil {
		return path
	}
	if strings.HasPrefix(path, home) {
		return "~" + path[len(home):]
	}
	return path
}
